server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anton-Shabalov/sos-config
          clone-on-start: true
  security:
    user:
      name: test
      password: test